[package]
name = "hkdray"
version = "0.1.0"
authors = ["hkdnet <satoko.itse@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"auto_ops" = "0.3.0"
